version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.99.101:31112
functions:
  trapeze-product-photos:
    lang: node10-express
    handler: ./product-photos
    image: prabkumar/trapeze-product-photos:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'securekvto'
      TABLE_PHOTO_REGISTRATIONS_NAME: 'photoRegistrationTable'
      HOST: 'mysql'
      USER: 'root'
      PASS: 'pass'
