version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.99.101:31112
functions:
  valve-product-photos-2-message:
    lang: node10-express
    handler: ./product-photos-2-message
    image: prabkumar/valve-product-photos-2-message:latest
