apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io.scrape: "false"
  creationTimestamp: "2019-10-11T19:56:24Z"
  generateName: product-photos-master-8576f4dfd7-
  labels:
    faas_function: product-photos-master
    pod-template-hash: 8576f4dfd7
  name: product-photos-master-8576f4dfd7-vl7sq
  namespace: openfaas-fn
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: product-photos-master-8576f4dfd7
    uid: 51f42e27-b8e9-48a5-a329-45fd6583786f
  resourceVersion: "113482"
  selfLink: /api/v1/namespaces/openfaas-fn/pods/product-photos-master-8576f4dfd7-vl7sq
  uid: 5ab68408-c3ab-44b3-8b05-c788b09b09a6
spec:
  containers:
  - env:
    - name: DBNAME
      value: helloRetail
    - name: HOST
      value: mysql.default.svc.cluster.local
    - name: PASS
      value: xyz
    - name: TABLE_CREDIT_CARDS_NAME
      value: creditCardsName
    - name: URL_ASSIGN
      value: http://gateway.openfaas:8080/function/product-photos-assign
    - name: URL_MESSAGE
      value: http://gateway.openfaas:8080/function/product-photos-2-message
    - name: URL_RECEIVE
      value: http://gateway.openfaas:8080/function/product-photos-3-receive
    - name: URL_RECORD
      value: http://gateway.openfaas:8080/function/product-photos-record
    - name: URL_REPORT
      value: http://gateway.openfaas:8080/function/product-photos-6-report
    - name: URL_SUCCESS
      value: http://gateway.openfaas:8080/function/product-photos-4-success
    - name: USER
      value: abc
    - name: fprocess
      value: node index.js
    image: prabkumar/product-photos-master:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /_/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 1
    name: product-photos-master
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /_/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      readOnlyRootFilesystem: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7pdfs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-7pdfs
    secret:
      defaultMode: 420
      secretName: default-token-7pdfs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-10-11T19:56:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-10-11T19:56:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-10-11T19:56:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-10-11T19:56:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5044c8952461479e773d5bcbb2ff414f281e95c4d5ed60e7b092830a71392fd1
    image: prabkumar/product-photos-master:latest
    imageID: docker-pullable://prabkumar/product-photos-master@sha256:26d17df704f18bc9f2171d744932d42140b48285ccc725f97cc43c05df5b70ab
    lastState: {}
    name: product-photos-master
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2019-10-11T19:56:26Z"
  hostIP: 10.0.2.15
  phase: Running
  podIP: 172.17.0.23
  podIPs:
  - ip: 172.17.0.23
  qosClass: BestEffort
  startTime: "2019-10-11T19:56:24Z"
