apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io.scrape: "false"
  creationTimestamp: "2020-01-25T12:01:11Z"
  generateName: trapeze-product-photos-6-report-7666b5b78b-
  labels:
    faas_function: trapeze-product-photos-6-report
    pod-template-hash: 7666b5b78b
  name: trapeze-product-photos-6-report-7666b5b78b-mcpw5
  namespace: openfaas-fn
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: trapeze-product-photos-6-report-7666b5b78b
    uid: 3f4a1065-566f-4738-99de-663d389224d0
  resourceVersion: "11350185"
  selfLink: /api/v1/namespaces/openfaas-fn/pods/trapeze-product-photos-6-report-7666b5b78b-mcpw5
  uid: e022bf7d-cef7-4063-bee1-80d05e777274
spec:
  containers:
  - env:
    - name: DBNAME
      value: helloRetail
    - name: HOST
      value: mysql.default.svc.cluster.local
    - name: PASS
      value: xyz
    - name: TABLE_PHOTO_ASSIGNMENTS_NAME
      value: photoAssignmentTable
    - name: TABLE_PHOTO_REGISTRATIONS_NAME
      value: photoRegistrationTable
    - name: USER
      value: abc
    - name: fprocess
      value: node index.js
    image: prabkumar/trapeze-product-photos-6-report:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /_/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 1
    name: trapeze-product-photos-6-report
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /_/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      readOnlyRootFilesystem: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7pdfs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-7pdfs
    secret:
      defaultMode: 420
      secretName: default-token-7pdfs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-25T12:01:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-25T12:01:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-25T12:01:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-25T12:01:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://059e0576575cbcf0b5863000a4b1fd9bb382d662833ca9656a2993a1315b33bf
    image: prabkumar/trapeze-product-photos-6-report:latest
    imageID: docker-pullable://prabkumar/trapeze-product-photos-6-report@sha256:2e91b52cbe09f5f3a17abd192b99815ebae21aaf82b7cf040fbb8eb8f7c8f259
    lastState: {}
    name: trapeze-product-photos-6-report
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-01-25T12:01:12Z"
  hostIP: 10.0.2.15
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2020-01-25T12:01:11Z"
